#!/usr/bin/env python
#
# pytelemeter GTK script 
# Shows some statistics from the "Mijn Telenet" page.
# 
# See COPYING for info about the license (GNU GPL)
# Check AUTHORS to see who wrote this software.

import gtk
from pytelemeter.GTK import PyTeleGui
import sys

def main():
	gtk.main()
	return 0       

if __name__ == "__main__":
	GUI = PyTeleGui(0)
	GUI.fillInfo(gtk.Button,1,None)
	GUI.show()
	main()
	sys.exit(0)
