#!/usr/bin/env python
#
# pytelemeter CLI script 
# Geeft download en upload statistieken van de Mijn Telenet pagina.
# 
# door Robbie Vanbrabant <robbie.vanbrabant@pandora.be>
# en Thomas Matthijs <knu@keanu.be>

from pytelemeter import Telemeter
import getopt, sys
from pytelemeter import VERSION
from datetime import date

def usage():
	print "\npytelemeter v%s" % VERSION
	print "http://pytelemeter.sourceforge.net"
	print "\nGebruik: " + sys.argv[0] + " [opties]"
	print "Opties:"
	print "  -h\ttoon dit"
	print "  -d\ttoon ook het dagoverzicht"
	print "  -m\tbereken max aantal MiB dat je vandaag kan downloaden\n"

def makeScale(perc,schaal):
	if (perc > 100):
		return "Overschreden!!".center(20)
	scale = ""
	aant = (float(perc)/schaal) * schaal/10
	scale += "=" * int(round(aant * schaal/10))
	scale += " " * int(round(schaal - (aant * schaal/10)))
	return scale

def printStats(meter):
	totalMib,uploadMib = meter.getVolumeUsed(0)
	totalProc,uploadProc = meter.getVolumeUsed(1)
	
	print "\nTelemeter statistieken: (%s)" % date.today()
	print "-------------------------------------"
	print "%s [%s] %5s MiB (%s%%)" % ("Volume verbruikt: ", makeScale(totalProc, 20), totalMib, totalProc)
	print "%s [%s] %5s MiB (%s%%)" % ("Upload verbruikt: ", makeScale(uploadProc, 20), uploadMib, totalProc)
	print ""

def printOverview(meter):
	overview = meter.getOverview()
	print "Telemeter dagoverzicht:"
	print "-----------------------"
	print "Dag      | Totaal | Upload"
	for date,total,upload in overview:
		print '%s | %6s | %6s' % (date,total,upload)
	print ""

def printMaxDownload(meter):
	totalMax, uploadMax = meter.getVolumeMax()
	overview = meter.getOverview()
	totalMib,uploadMib = meter.getVolumeUsed(0)
	
	totalMax = totalMax*1024
	uploadMax = uploadMax*1024

	if (totalMax <= uploadMib):
		print "%s %i MiB. U gaat er terug onder op: %s" % ("U bent over uw limiet met", (totalMib - totalMax),meter.getDateBroad())
	else:
		print "%s %i %s" % ("U mag vandaag max",totalMax - totalMib + int(overview[0][1]),"MiB downloaden om niet over uw limiet te gaan.")
	
	if (uploadMax <= uploadMib):
		print "%s %i MiB. U gaat er terug onder op: %s" % ("U bent over uw limiet met", (uploadMib * uploadMax),meter.getDateBroad())
	else:
		print "%s %i %s" % ("U mag vandaag max",uploadMax - uploadMib + int(overview[0][2]),"MiB uploaden om niet over uw limiet te gaan.")
	print ""

def main():
	try:
		o, a = getopt.getopt(sys.argv[1:], ":hdm")
	except getopt.GetoptError:
		usage()
		sys.exit(2)
		
	showDay = 0
	showMax = 0
	opts = {}
	for k,v in o:
		opts[k] = v
	if opts.has_key('-h') or opts.has_key('--help'):
		usage()
		sys.exit()
	if opts.has_key("-d"):
		showDay = 1 
	if opts.has_key("-m"):
		showMax = 1

	meter = Telemeter()

	meter.fetch()

	printStats(meter)

	if showMax == 1:
		printMaxDownload(meter)
	if showDay == 1:
		printOverview(meter)

if __name__ == "__main__":
	main()
	sys.exit(0)
