<!-- Cool links -->

<h4>Links</h4>
<p>
<ul>
<li><a href="http://mijn.telenet.be">Mijn Telenet</a></li>
<li><a href="http://www.tik.be">Telenet Internet Klantenvereniging</a></li>
<br/>
<li><a href="http://www.telemeter.be">Telemeter</a> (Windows and Mac)</li>
<li><a href="http://www.ispmonitor.be">ISP Monitor</a> (Windows)</li>
<li><a href="http://sourceforge.net/projects/phptelemeter/">phptelemeter</a> (Linux)</li>
</ul>
</p>

