<!-- Personal info -->
<a name="start"></a>
<h4>Start</h4>
<p>
Pytelemeter is a small Python "Telemeter" application to check out Telenet's download/upload statistics.<br>
Make sure you agree to all the terms stated in the COPYING file (GNU GPL v2) before you use this software.<br>
<br>
</p>


<b>22/01/2011</b>
<br>
 This project has been abandoned. For the latest sources, please from now on refer to <a href="https://github.com/robbiev/pytelemeter">GitHub</a>. 
<br>
<br>


<b>29/01/2009</b>
<br>
 <a href="?down">Version 1.5</a>  was released. You can now also install pytelemeter from a repository.
<br>
<br>

<b>21/07/2006</b>
<br>
Added Debian and Gentoo package links on the <a href="?down">download page</a>. Thanks Joris and bravecobra!
<br>
<br>

<b>12/02/2006</b>
<br>
pytelemeter is alive and kicking! Today <a href="?down">version 1.4</a> was released,
with support for the new telemeter. (check out the
<a href="https://sourceforge.net/project/screenshots.php?group_id=99970">new tray icon</a>)
<br>
<br>
</p>
