<!-- Support -->

<a name="support"></a>
<h4>Support</h4>
<p>
<u><b>Mailing lists</b></u><br>
Feel free to subscribe to the <a href="https://lists.sourceforge.net/lists/listinfo/pytelemeter-support">pytelemeter-support</a> mailing list to get support, ask questions, make suggestions, ...<br/>
To keep yourself informed about new releases etc. subscribe to <a href="https://lists.sourceforge.net/lists/listinfo/pytelemeter-news">pytelemeter-news</a>!<br>
Note that you do not need to subscribe for a single support request, just send a mail to <a href="mailto:pytelemeter-support@lists.sourceforge.net">pytelemeter-support@lists.sourceforge.net</a>.
</p>
<p>
<u><b>FAQ</b></u><br>
<b>Q:</b> I can't install pytelemeter on my Debian system, I get an "ImportError: No module named distutils.core" error!<br>
<b>A:</b> Install the python-dev package.<br><br>

<b>Q:</b> I can't run pytelemeter-gtk, I get an "RuntimeError: could not open display" error!<br> 
<b>A:</b> Set your DISPLAY environment variable, usually this means: export DISPLAY=:0 (when this faq item occurs, mail us).<br><br>

<b>Q:</b> I can't install pytelemeter on my Mandrake system, I get an "invalid Python installation: unable to open /usr/lib/python2.x/config/Makefile" error!<br>
<b>A:</b> Install the libpython2.x-devel package (in addition to python, python-devel).
<br><br>
<b>Q:</b> I am a Gentoo geek and pytelemeter doesn't work on my lightning fast optimized system!<br>
<b>A:</b> Make sure you put SSL support in your USE flags before installing Python.
<br><br>
<b>Q:</b> I can't create an RPM using distutil's bdist_rpm, I get an "AssertionError: unexpected number of RPM files found" error!<br>
<b>A:</b> This is in fact a distutils bug. Upgrade to Python >= 2.4.
</p>

